# Generated by Django 5.1.2 on 2024-12-14 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0002_campaign_urgent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('donor_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='campaign.campaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='donation_photos/')),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('object', 'Objet'), ('food', 'Nourriture')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('availability', models.CharField(choices=[('weekdays', 'Journée en semaine'), ('weekend', 'Weekend'), ('flexible', 'Flexible')], max_length=10)),
                ('condition', models.CharField(choices=[('like_new', 'Comme neuf'), ('good', 'Bon état'), ('average', 'État moyen'), ('to_repair', 'À bricoler')], max_length=20)),
                ('expiration_date', models.DateField(blank=True, help_text='Applicable uniquement pour la nourriture', null=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
