# Generated by Django 5.1.2 on 2025-01-06 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_delete_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='objectdonation',
            name='photos',
        ),
        migrations.AlterField(
            model_name='objectdonation',
            name='availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.availabilitychoices'),
        ),
        migrations.AlterField(
            model_name='objectdonation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.categorychoices'),
        ),
        migrations.AlterField(
            model_name='objectdonation',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.conditionchoices'),
        ),
        migrations.CreateModel(
            name='PhotoObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='donation_photos/')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.objectdonation')),
            ],
        ),
    ]
