# Generated by Django 5.1.2 on 2025-01-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_availabilitychoices_categorychoices_conditionchoices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectdonation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
