# Generated by Django 5.1.2 on 2024-12-14 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('beneficiary', models.CharField(max_length=255)),
                ('beneficiary_phone', models.CharField(max_length=15)),
                ('goal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration', models.IntegerField(help_text='Durée en jours')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('reward', models.TextField(blank=True, null=True)),
                ('uploaded_files', models.FileField(blank=True, null=True, upload_to='campaign_files/')),
                ('visibility', models.CharField(choices=[('public', 'Publique'), ('private', 'Privée')], default='public', max_length=10)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('encours', 'Encours'), ('terminee', 'Terminee')], default='encours', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign.category')),
            ],
        ),
    ]
