# Generated by Django 5.1.2 on 2024-12-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_association_particulier_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='pseudo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='particulier',
            name='pseudo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
